# Generated by Django 4.1 on 2023-12-31 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamberry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, null=True, through='streamberry.Avaliacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filme',
            name='streamings',
            field=models.ManyToManyField(blank=True, null=True, to='streamberry.streaming'),
        ),
    ]
