# Generated by Django 4.1 on 2023-12-31 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamberry', '0002_alter_filme_avaliacoes_alter_filme_streamings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filme',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, through='streamberry.Avaliacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filme',
            name='streamings',
            field=models.ManyToManyField(blank=True, to='streamberry.streaming'),
        ),
    ]
